### ISSUE TITLE
src/Preprocess.cu 和 src/Decode.cu好像在include/Yolov9.h没引用，是咋关联起来的？

### ISSUE THREAD

**Issue by zranguai** [LinhanDai/yolov9-tensorrt#2]
例如[这里](https://github.com/LinhanDai/yolov9-tensorrt/blob/7729c915733543c76a6ae9afb77d5a8825f924c0/include/Yolov9.h#L95)使用了preprocess_kernel_img，但是该文件上面没引用Preprocess.cu文件。

**Comment by LinhanDai** [comment]
CmakeList.txt文件中有把.cu文件变成动态库，通过extern "C"可以链接在动态库里面找到相应为函数链接入口

**Comment by LinhanDai** [comment]
> 例如[这里](https://github.com/LinhanDai/yolov9-tensorrt/blob/7729c915733543c76a6ae9afb77d5a8825f924c0/include/Yolov9.h#L95)使用了preprocess_kernel_img，但是该文件上面没引用Preprocess.cu文件。

CmakeList.txt文件中有把.cu文件变成动态库，通过extern "C"可以链接在动态库里面找到相应为函数链接入口

**Comment by zranguai** [comment]
懂了 谢谢大佬解析
